const Sequelize = require('sequelize');
const dbConfig = require('../config/database');
const connection = new Sequelize(dbConfig);
const User = require('../models/User');
const Registered = require('../models/Registered');
const Admin = require('../models/Admin');
Admin.init(connection);
Registered.init(connection);
User.init(connection);
module.exports = connection;