const Sequelize = require('sequelize');
const dbConfig = require('../config/database');
// const Carro = require('../models/Carro');
const connection = new Sequelize(dbConfig);
const Usuario = require('../models/Usuario');
const Inscrito = require('../models/Inscrito');
const Admin = require('../models/Admin');
// Carro.init(connection);
//Carro.associate(connection.models);
Admin.init(connection);
Inscrito.init(connection);
Usuario.init(connection);
// Usuario.associate(connection.models);
module.exports = connection;